import { GameElementSpecificationsInterface } from "./../../interfaces/game-element-specifications-interface";
import { AlingString, ColorsString, GameFontStylesString, textFontSize } from "./../../settings/game-constants-strings/text-styles-string";

export const mainSceneElementSpecifictions: GameElementSpecificationsInterface[] = [
    {
        type: 'image',
        element: 'background',
        assetName: 'main-scene-background',
        // assetName: 'boot-load-background',
        name: 'main-scene-background',
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            // objectWidth: 1366,
            objectWidth: 1366,
            objectHeight: 770,
            // objectWidth: 1480,
            // objectHeight: 870,
            objectPositionX: 683,
            objectPositionY: 384,
        }
    },
    {
        type: 'text',
        element: 'title',
        name: 'game-title',
        content: 'JUEGO SERIO GIRHA\nRÍO SAN PEDRO - CHISINCHE',
        style: {
            fontFamily: GameFontStylesString.BIG_FONT,
            color: ColorsString.WHITE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            stroke: ColorsString.DARK_GRAY_HEXADECIMAL_STRING,
            // stroke: ColorsString.DARK_GREEN_HEXADECIMAL_STRING,
            // stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
            // stroke: ColorsString.DARK_GRAY_HEXADECIMAL_STRING,
            // stroke: ColorsString.DARK_GREEN_HEXADECIMAL_STRING,
            strokeThickness: textFontSize.Regular.strokeThickness,
            fontSize: '70px',
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 1340,
            objectHeight: 200,
            objectPositionX: 683,
            objectPositionY: 400,
        }
    },
    {
        
        type: 'button',
        element: 'simple-button',
        assetName: 'play-game-button-background',
        name: 'play-button',
        content: 'JUGAR',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.WHITE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Big.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 380,
            objectHeight: 160,
            objectPositionX: 1080,
            objectPositionY: 642,
        }
    },
    {
        type: 'button',
        element: 'bottom-title-button',
        assetName: 'info-icon-background',
        content: 'INFORMACIÓN',
        name: 'info-button',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.BLACK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
            // strokeThickness: textFontSize.Small.strokeThickness,
            // fontSize: textFontSize.Small.fontSize,
            strokeThickness: textFontSize.VerySmall.strokeThickness,
            fontSize: textFontSize.VerySmall.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 71,
            objectHeight: 100,
            // objectWidth: 100,
            // objectHeight: 140,
            objectPositionX: 180,
            objectPositionY: 666,
        }
    },
    {
        type: 'button',
        element: 'bottom-title-button',
        assetName: 'help-icon-background',
        name: 'help-button',
        content: 'AYUDA',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.BLACK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
            // strokeThickness: textFontSize.Small.strokeThickness,
            // fontSize: textFontSize.Small.fontSize,
            strokeThickness: textFontSize.VerySmall.strokeThickness,
            fontSize: textFontSize.VerySmall.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 71,
            objectHeight: 100,
            // objectWidth: 100,
            // objectHeight: 140,
            objectPositionX: 360,
            objectPositionY: 666,
        },
    },
    // {
    //     type: 'button',
    //     element: 'bottom-title-button',
    //     assetName: 'on-sound-icon-background',
    //     name: 'sound-button',
    //     content: 'SONIDO',
    //     style: {
    //         fontFamily: GameFontStylesString.BASE_FONT,
    //         color: ColorsString.BLACK_HEXADECIMAL_STRING,
    //         align: AlingString.CENTER_STRING,
    //         stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
    //         // strokeThickness: textFontSize.Small.strokeThickness,
    //         // fontSize: textFontSize.Small.fontSize,
    //         strokeThickness: textFontSize.VerySmall.strokeThickness,
    //         fontSize: textFontSize.VerySmall.fontSize,
    //     },
    //     scale: {
    //         objectWidthRatio: 1,
    //         objectHeightRatio: 1,
    //         objectWidth: 71,
    //         objectHeight: 100,
    //         // objectWidth: 100,
    //         // objectHeight: 140,
    //         objectPositionX: 520,
    //         objectPositionY: 666,
    //     }
    // },
    {
        type: 'button',
        element: 'bottom-title-button',
        assetName: 'score-icon-background',
        content: 'PUNTUACIONES',
        name: 'score-button',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.BLACK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
            // strokeThickness: textFontSize.Small.strokeThickness,
            // fontSize: textFontSize.Small.fontSize,
            strokeThickness: textFontSize.VerySmall.strokeThickness,
            fontSize: textFontSize.VerySmall.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 71,
            objectHeight: 100,
            // objectPositionX: 695,
            // objectPositionY: 666,
            objectPositionX: 520,
            objectPositionY: 666,
        }
    }
]