import { GameElementSpecificationsInterface } from "../../interfaces/game-element-specifications-interface";
import { AlingString, ColorsString, GameFontStylesString, textFontSize } from "../../settings/game-constants-strings/text-styles-string";

export const endSceneElementsSpecifications: GameElementSpecificationsInterface[] = [
    {
        type: 'image',
        element: 'background',
        assetName: 'modal-scene-background',
        name: 'scene-backgroud',
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 810,
            objectHeight: 630,
            objectPositionX: 405,
            objectPositionY: 315,
        }
    },
    {
        type: 'image',
        element: 'background',
        assetName: 'panel-card-2-background',
        name: 'panel-backgroud',
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            // objectWidth: 1066,
            objectWidth: 754,
            objectHeight: 580,
            objectPositionX: 405,
            objectPositionY: 315,
        },
    },
    {
        type: 'image',
        element: 'background',
        assetName: 'scene-title-background',
        name: 'scene-title-background',
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 572,
            objectHeight: 100,
            objectPositionX: 405,
            // objectPositionY: 154,
            // objectPositionY: 120,
            objectPositionY: 113,
        }
    },
    {
        type: 'text',
        element: 'title',
        name: 'scene-title',
        content: 'JUEGO TERMINADO',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.WHITE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Regular.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 700,
            objectHeight: 40,
            objectPositionX: 405,
            objectPositionY: 113,
        }
    },
    {
        type: 'text',
        element: 'title',
        name: 'total-score-text',
        content: 'PUNTAJE TOTAL: 0',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.RED_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Medium.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 600,
            objectHeight: 35,
            objectPositionX: 405,
            objectPositionY: 191,
        },
    },
    /**************************************************************************/
    {
        type: 'text',
        element: 'title',
        name: 'period-20-30-title',
        content: 'PERIODO\n2020 - 2030',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_PINK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.LitleVerySmall.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 320,
            objectPositionY: 247,
        },
    },
    {
        type: 'text',
        element: 'title',
        name: 'period-30-40-title',
        content: 'PERIODO\n2030 - 2040',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_PINK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.LitleVerySmall.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 482,
            objectPositionY: 247,
        },
    },
    {
        type: 'text',
        element: 'title',
        name: 'period-40-50-title',
        content: 'PERIODO\n2040 - 2050',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_PINK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.LitleVerySmall.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 644,
            objectPositionY: 247,
        },
    },
    /**************************************************************************/
    
    {
        type: 'text',
        element: 'title',
        name: 'acus-title',
        content: 'ACUS',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_PINK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.LitleVerySmall.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 160,
            objectPositionY: 306,
        },
    },
    {
        type: 'text',
        element: 'title',
        name: 'hydroelectric-title',
        content: 'Hidroeléctrica',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_PINK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.LitleVerySmall.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 160,
            objectPositionY: 360,
        },
    },
    {
        type: 'text',
        element: 'title',
        name: 'coverage-title',
        content: 'Cobertura de\nla Demanda',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_PINK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.LitleVerySmall.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 160,
            objectPositionY: 414,
        },
    },
    {
        type: 'text',
        element: 'title',
        name: 'river-health-title',
        content: 'Salud\ndel Río',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_PINK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.LitleVerySmall.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 160,
            objectPositionY: 468,
        },
    },

    /**************************************************************************/
    ///////////////////////////////////////////////////////
    {
        type: 'text',
        element: 'score',
        name: 'acus-20-30-text',
        content: '0',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_BLUE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 320,
            objectPositionY: 306,
        },
    },
    {
        type: 'text',
        element: 'score',
        name: 'acus-30-40-text',
        content: '0',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_BLUE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 482,
            objectPositionY: 306,
        },
    },
    {
        type: 'text',
        element: 'score',
        name: 'acus-40-50-text',
        content: '0',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_BLUE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 644,
            objectPositionY: 306,
        },
    },
    ///////////////////////////////////////////////////////
    {
        type: 'text',
        element: 'score',
        name: 'hydroelectric-20-30-text',
        content: '0',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_BLUE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 320,
            objectPositionY: 360,
        },
    },
    {
        type: 'text',
        element: 'score',
        name: 'hydroelectric-30-40-text',
        content: '0',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_BLUE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 482,
            objectPositionY: 360,
        },
    },
    {
        type: 'text',
        element: 'score',
        name: 'hydroelectric-40-50-text',
        content: '0',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_BLUE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 644,
            objectPositionY: 360,
        },
    },
    ///////////////////////////////////////////////////////
    {
        type: 'text',
        element: 'score',
        name: 'coverage-20-30-text',
        content: '0',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_BLUE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 320,
            objectPositionY: 414,
        },
    },
    {
        type: 'text',
        element: 'score',
        name: 'coverage-30-40-text',
        content: '0',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_BLUE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 482,
            objectPositionY: 414,
        },
    },
    {
        type: 'text',
        element: 'score',
        name: 'coverage-40-50-text',
        content: '0',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_BLUE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 644,
            objectPositionY: 414,
        },
    },
    ///////////////////////////////////////////////////////
    {
        type: 'text',
        element: 'score',
        name: 'river-health-20-30-text',
        content: '0',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_BLUE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 320,
            objectPositionY: 468,
        },
    },
    {
        type: 'text',
        element: 'score',
        name: 'river-health-30-40-text',
        content: '0',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_BLUE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 482,
            objectPositionY: 468,
        },
    },
    {
        type: 'text',
        element: 'score',
        name: 'river-health-40-50-text',
        content: '0',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_BLUE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 150,
            objectHeight: 50,
            objectPositionX: 644,
            objectPositionY: 468,
        },
    },


    /**************************************************************************/
    
    {
        type: 'button',
        element: 'simple-button',
        assetName: 'next-button-background',
        name: 'quit-button',
        content: 'SALIR',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.WHITE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.Small.fontSize
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 200,
            objectHeight: 60,
            objectPositionX: 550,
            objectPositionY: 540,
        }
    }
]
