import { GameElementSpecificationsInterface } from "../../interfaces/game-element-specifications-interface";
import { AlingString, ColorsString, GameFontStylesString, textFontSize } from "../../settings/game-constants-strings/text-styles-string";

export const mapSceneElemntSpecifictions: GameElementSpecificationsInterface[] = [
    {
        type: 'image',
        element: 'background',
        assetName: 'map-background',
        name: 'map-scene-background',
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            // objectWidth: 1366,
            objectWidth: 810,
            objectHeight: 630,
            objectPositionX: 405,
            objectPositionY: 315,
        }
    },
    {
        type: 'image',
        element: 'background',
        assetName: 'modal-scene-background',
        name: 'scene-backgroud',
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 810,
            objectHeight: 630,
            objectPositionX: 405,
            objectPositionY: 315,
        }
    },
    {
        type: 'text',
        element: 'title',
        name: 'game-title',
        content: 'CUENCA DEL\nRÍO SAN PEDRO - CHISINCHE',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.RED_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
            strokeThickness: textFontSize.Medium.strokeThickness,
            fontSize: '30px',
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 600,
            objectHeight: 40,
            objectPositionX: 405,
            objectPositionY: 70,
        }
    },
    {
        type: 'button',
        element: 'bottom-title-button',
        assetName: 'home-icon-background',
        content: 'INICIO',
        name: 'home-button',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.BLACK_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
            strokeThickness: textFontSize.VerySmall.strokeThickness,
            fontSize: textFontSize.VerySmall.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 65,
            objectHeight: 86,
            objectPositionX: 78,
            objectPositionY: 70,
        }
    },
    {
        type: 'text',
        element: 'title',
        content: 'PUNTOS: 0',
        name: 'total-score',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.DARK_PURPLE_HEXADECIMAL_STRING,
            align: AlingString.RIGHT_STRING,
            stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
            strokeThickness: textFontSize.Small.strokeThickness,
            fontSize: textFontSize.Small.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 450,
            objectHeight: 40,
            objectPositionX: 775,
            objectPositionY: 26,
        },
        originX: 1,
        originY: 0
    },
    {
        
        type: 'button',
        element: 'simple-button',
        assetName: 'play-game-button-background',
        name: 'continue-button',
        content: 'TOMAR DECISIÓN',
        style: {
            fontFamily: GameFontStylesString.BASE_FONT,
            color: ColorsString.WHITE_HEXADECIMAL_STRING,
            align: AlingString.CENTER_STRING,
            fontSize: textFontSize.VerySmall.fontSize,
        },
        scale: {
            objectWidthRatio: 1,
            objectHeightRatio: 1,
            objectWidth: 250,
            objectHeight: 50,
            objectPositionX: 630,
            objectPositionY: 580,
        }
    },
    // {
    //     type: 'button',
    //     element: 'bottom-title-button',
    //     assetName: 'info-icon-background',
    //     content: 'INFORMACIÓN',
    //     name: 'info-button',
    //     style: {
    //         fontFamily: GameFontStylesString.BASE_FONT,
    //         color: ColorsString.BLACK_HEXADECIMAL_STRING,
    //         align: AlingString.CENTER_STRING,
    //         stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
    //         // strokeThickness: textFontSize.Small.strokeThickness,
    //         // fontSize: textFontSize.Small.fontSize,
    //         strokeThickness: textFontSize.VerySmall.strokeThickness,
    //         fontSize: textFontSize.VerySmall.fontSize,
    //     },
    //     scale: {
    //         objectWidthRatio: 1,
    //         objectHeightRatio: 1,
    //         objectWidth: 71,
    //         objectHeight: 100,
    //         // objectWidth: 100,
    //         // objectHeight: 140,
    //         objectPositionX: 180,
    //         objectPositionY: 666,
    //     }
    // },
    // {
    //     type: 'button',
    //     element: 'bottom-title-button',
    //     assetName: 'help-icon-background',
    //     name: 'help-button',
    //     content: 'AYUDA',
    //     style: {
    //         fontFamily: GameFontStylesString.BASE_FONT,
    //         color: ColorsString.BLACK_HEXADECIMAL_STRING,
    //         align: AlingString.CENTER_STRING,
    //         stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
    //         // strokeThickness: textFontSize.Small.strokeThickness,
    //         // fontSize: textFontSize.Small.fontSize,
    //         strokeThickness: textFontSize.VerySmall.strokeThickness,
    //         fontSize: textFontSize.VerySmall.fontSize,
    //     },
    //     scale: {
    //         objectWidthRatio: 1,
    //         objectHeightRatio: 1,
    //         objectWidth: 71,
    //         objectHeight: 100,
    //         // objectWidth: 100,
    //         // objectHeight: 140,
    //         objectPositionX: 360,
    //         objectPositionY: 666,
    //     },
    // },
    // {
    //     type: 'button',
    //     element: 'bottom-title-button',
    //     assetName: 'on-sound-icon-background',
    //     name: 'sound-button',
    //     content: 'SONIDO',
    //     style: {
    //         fontFamily: GameFontStylesString.BASE_FONT,
    //         color: ColorsString.BLACK_HEXADECIMAL_STRING,
    //         align: AlingString.CENTER_STRING,
    //         stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
    //         // strokeThickness: textFontSize.Small.strokeThickness,
    //         // fontSize: textFontSize.Small.fontSize,
    //         strokeThickness: textFontSize.VerySmall.strokeThickness,
    //         fontSize: textFontSize.VerySmall.fontSize,
    //     },
    //     scale: {
    //         objectWidthRatio: 1,
    //         objectHeightRatio: 1,
    //         objectWidth: 71,
    //         objectHeight: 100,
    //         // objectWidth: 100,
    //         // objectHeight: 140,
    //         objectPositionX: 520,
    //         objectPositionY: 666,
    //     }
    // },
    // {
    //     type: 'button',
    //     element: 'bottom-title-button',
    //     assetName: 'score-icon-background',
    //     content: 'PUNTUACIONES',
    //     name: 'score-button',
    //     style: {
    //         fontFamily: GameFontStylesString.BASE_FONT,
    //         color: ColorsString.BLACK_HEXADECIMAL_STRING,
    //         align: AlingString.CENTER_STRING,
    //         stroke: ColorsString.WHITE_HEXADECIMAL_STRING,
    //         // strokeThickness: textFontSize.Small.strokeThickness,
    //         // fontSize: textFontSize.Small.fontSize,
    //         strokeThickness: textFontSize.VerySmall.strokeThickness,
    //         fontSize: textFontSize.VerySmall.fontSize,
    //     },
    //     scale: {
    //         objectWidthRatio: 1,
    //         objectHeightRatio: 1,
    //         objectWidth: 71,
    //         objectHeight: 100,
    //         // objectWidth: 100,
    //         // objectHeight: 140,
    //         objectPositionX: 695,
    //         objectPositionY: 666,
    //     }
    // }
]